"""
RevenueMD AI enhancement layer — Anthropic Claude.

Runs after the deterministic rules engine to:
- Enrich issue descriptions with plain-language context
- Catch edge cases the rule modules don't cover
- Generate a natural, actionable summary in EN + ES
- Add a biller-facing note for complex situations

Falls back silently to the rules-engine result if:
- ANTHROPIC_API_KEY is not set
- The anthropic package is not installed
- The API call fails for any reason
"""
from __future__ import annotations

import base64
import json
import logging
import os
from typing import Any, Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)

MODEL = "claude-haiku-4-5-20251001"

try:
    import anthropic as _anthropic_module
    _API_KEY = os.getenv("ANTHROPIC_API_KEY", "")
    _client = _anthropic_module.Anthropic(api_key=_API_KEY) if _API_KEY else None
except ImportError:
    _client = None


def is_available() -> bool:
    return _client is not None


def appeal_letter(denial: Dict[str, Any], lang: str = "en") -> str:
    """
    Generate a formal first-level appeal letter for a denied claim.
    Falls back to a structured template if AI is unavailable.
    """
    from datetime import date
    date_str = date.today().strftime("%B %d, %Y") if lang == "en" else date.today().strftime("%d de %B de %Y")

    if not is_available():
        return _appeal_template(denial, lang, date_str)

    try:
        is_en = lang == "en"
        prompt = f"""You are a certified medical billing specialist for Puerto Rico payers (ASES/Mi Salud, Plan Vital, Triple-S, MMM, MCS, Medicare/FCSO).

Write a formal first-level appeal letter for the following denied claim. The letter must:
- Be professional and factual
- Cite the specific regulatory basis (ASES Provider Manual 2024, AMA CPT guidelines, CMS Pub 100-04, PR Law 194-2000 as applicable)
- Request reconsideration and full payment within the regulatory timeframe
- Be written in {"English" if is_en else "Spanish"}
- Be ready to send — include placeholders like [PROVIDER NAME] and [NPI] where needed
- Be concise: 3-4 paragraphs plus a closing

CLAIM DETAILS:
- Claim ID: {denial.get("id", "N/A")}
- Denial reason: {denial.get("rEn" if is_en else "rEs", "Not specified")}
- Amount in dispute: ${denial.get("lost", 0):,.2f}
- Days remaining to appeal: {denial.get("days", "N/A")}

Return ONLY the letter text — no JSON, no markdown, no preamble."""

        response = _client.messages.create(
            model=MODEL,
            max_tokens=1200,
            temperature=0,
            messages=[{"role": "user", "content": prompt}],
        )
        return f"{date_str}\n\n" + response.content[0].text.strip()

    except Exception as exc:
        logger.warning("Appeal letter generation failed, using template: %s", exc)
        return _appeal_template(denial, lang, date_str)


def _appeal_template(denial: Dict[str, Any], lang: str, date_str: str) -> str:
    is_en = lang == "en"
    claim_id = denial.get("id", "N/A")
    reason_en = denial.get("rEn", "Claim denied")
    reason_es = denial.get("rEs", "Reclamo denegado")
    amount = denial.get("lost", 0)

    if is_en:
        return (
            f"{date_str}\n\n"
            f"Re: First-Level Appeal — Claim #{claim_id}\n"
            f"Payer: Plan Vital / ASES Mi Salud\n"
            f"Denial Reason: {reason_en}\n"
            f"Amount in Dispute: ${amount:,.2f}\n\n"
            f"Dear Provider Relations Department,\n\n"
            f"We formally appeal the denial of Claim #{claim_id} on behalf of [PROVIDER NAME], NPI [NPI]. "
            f"The claim was denied citing: \"{reason_en}\". We respectfully request reconsideration.\n\n"
            f"The services rendered were medically necessary and fully documented per ASES/Plan Vital behavioral "
            f"health guidelines (ASES Provider Manual 2024, §5.2; AMA CPT 2024). All submitted codes are "
            f"appropriate for the documented level of service (CMS Pub 100-04, Ch. 12).\n\n"
            f"Enclosed: (a) complete clinical note, (b) active treatment plan with supervising clinician signature, "
            f"(c) prior authorization confirmation if applicable, (d) this appeal letter with citations.\n\n"
            f"We request full payment within the regulatory timeframe. Please contact our billing office with questions.\n\n"
            f"Sincerely,\n[PROVIDER NAME]\nBilling Department\n\n"
            f"— Generated by RevenueMD Pre-Submission Intelligence"
        )
    else:
        return (
            f"{date_str}\n\n"
            f"Re: Apelación de Primer Nivel — Reclamo #{claim_id}\n"
            f"Pagador: Plan Vital / ASES Mi Salud\n"
            f"Razón de Denegación: {reason_es}\n"
            f"Monto en Disputa: ${amount:,.2f}\n\n"
            f"Estimado Departamento de Relaciones con Proveedores,\n\n"
            f"Apelamos formalmente la denegación del Reclamo #{claim_id} en nombre de [NOMBRE DEL PROVEEDOR], "
            f"NPI [NPI]. El reclamo fue denegado citando: \"{reason_es}\". Solicitamos respetuosamente reconsideración.\n\n"
            f"Los servicios prestados fueron médicamente necesarios y están documentados conforme a las guías de "
            f"salud conductual de ASES/Plan Vital (Manual del Proveedor ASES 2024, §5.2; AMA CPT 2024). Los "
            f"códigos sometidos son apropiados para el nivel de servicio (CMS Pub 100-04, Cap. 12).\n\n"
            f"Se adjunta: (a) nota clínica completa, (b) plan de tratamiento vigente con firma del supervisor, "
            f"(c) autorización previa si aplica, (d) esta carta con citas regulatorias.\n\n"
            f"Solicitamos pago completo dentro del término reglamentario.\n\n"
            f"Atentamente,\n[NOMBRE DEL PROVEEDOR]\nDepartamento de Facturación\n\n"
            f"— Generado por RevenueMD Pre-Submission Intelligence"
        )


def enhance(result: Dict[str, Any]) -> Dict[str, Any]:
    """
    Takes a ScrubResult dict from the rules engine, calls Claude to enrich it.
    Returns a modified copy (or the original if AI is unavailable or call fails).
    """
    if not is_available():
        return result

    try:
        claim_info = {
            "id":        result.get("id"),
            "payer":     result.get("payer"),
            "codes":     result.get("codes"),
            "dos":       result.get("dos"),
            "billed":    result.get("billed"),
            "auth":      result.get("auth") or "None",
            "pos":       result.get("pos", "11"),
            "npi":       result.get("npi") or "Not provided",
            "diagnoses": result.get("diagnoses", []),
        }

        issues = result.get("issues", [])
        fixes  = result.get("fix", [])
        risk   = result.get("risk", 0)
        lane   = result.get("lane", "auto_clear")

        prompt = f"""You are a certified medical billing expert for Puerto Rico payers \
(ASES/Mi Salud, Plan Vital, Triple-S, MMM, MCS, Medicare/FCSO).

A claim was processed by a deterministic rules engine. Enhance the findings.

CLAIM:
{json.dumps(claim_info, indent=2)}

RULES ENGINE FINDINGS:
- Risk score: {risk}/100
- Triage lane: {lane}
- Issues: {json.dumps(issues, indent=2)}
- Suggested fixes: {json.dumps(fixes, indent=2)}

Your tasks:
1. Write a concise 2-3 sentence summary (sEn in English, sEs in Spanish) for the billing professional.
2. Review the issues list — improve descriptions, correct errors, add issues the engine missed \
(use code prefix "AI-" for new ones).
3. Review the fix list — improve instructions, add missing fixes, order by urgency.
4. If there is a compliance risk or nuance worth highlighting separately, write a brief ai_note \
(1-2 sentences max). Otherwise leave it an empty string.

Issue schema: {{"code":"string","sev":"error|warning|info","tEn":"Short EN","tEs":"Short ES","dEn":"Detail EN","dEs":"Detail ES"}}
Fix schema: {{"tEn":"Title EN","tEs":"Title ES","wEn":"What to do EN","wEs":"What to do ES"}}

Respond with ONLY valid JSON — no markdown fences, no prose outside the JSON object:
{{
  "sEn": "...",
  "sEs": "...",
  "issues": [...],
  "fix": [...],
  "ai_note": "..."
}}"""

        response = _client.messages.create(
            model=MODEL,
            max_tokens=1800,
            temperature=0,
            messages=[{"role": "user", "content": prompt}],
        )

        raw = response.content[0].text.strip()
        if raw.startswith("```"):
            parts = raw.split("```")
            raw = parts[1] if len(parts) > 1 else raw
            if raw.startswith("json"):
                raw = raw[4:].strip()

        ai = json.loads(raw)

        enhanced = result.copy()
        if ai.get("sEn"):
            enhanced["sEn"] = ai["sEn"]
        if ai.get("sEs"):
            enhanced["sEs"] = ai["sEs"]
        if ai.get("issues"):
            enhanced["issues"] = ai["issues"]
        if ai.get("fix"):
            enhanced["fix"] = ai["fix"]
        enhanced["ai_note"]     = ai.get("ai_note", "") or ""
        enhanced["ai_enhanced"] = True

        return enhanced

    except Exception as exc:
        logger.warning("AI enhancement failed — using rules-engine result: %s", exc)
        return result


_IMAGE_MIME_BY_EXT = {
    ".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg",
    ".gif": "image/gif", ".webp": "image/webp",
}


def _file_content_block(filename: str, data: bytes) -> Optional[Dict[str, Any]]:
    """Build a Claude vision content block for an image or PDF file, or None
    if the extension isn't a supported document/image type."""
    ext = os.path.splitext(filename.lower())[1]
    if ext == ".pdf":
        return {
            "type": "document",
            "source": {"type": "base64", "media_type": "application/pdf", "data": base64.b64encode(data).decode()},
        }
    media_type = _IMAGE_MIME_BY_EXT.get(ext)
    if not media_type:
        return None
    return {
        "type": "image",
        "source": {"type": "base64", "media_type": media_type, "data": base64.b64encode(data).decode()},
    }


def smart_entry_extract(
    claim_text: str,
    record_files: List[Tuple[str, bytes]],
    claim_files: List[Tuple[str, bytes]],
    lang: str = "en",
) -> Optional[Dict[str, Any]]:
    """
    Reads medical-record page(s) and claim-lines screenshots/text via Claude
    vision, extracts billable line items, and cross-references them against
    the record for documentation gaps and coding-risk issues.

    Returns {"lines": [...], "docFindings": [...], "issues": [...]} or None
    if AI is unavailable, there's nothing to analyze, or the call fails.
    """
    if not is_available():
        return None
    if not claim_text.strip() and not claim_files and not record_files:
        return None

    is_en = lang != "es"
    content: List[Dict[str, Any]] = []

    if record_files:
        content.append({"type": "text", "text": "MEDICAL RECORD PAGE(S):"})
        for filename, data in record_files:
            block = _file_content_block(filename, data)
            if block:
                content.append(block)

    if claim_files:
        content.append({"type": "text", "text": "CLAIM LINES WORKSHEET / SCREENSHOT(S):"})
        for filename, data in claim_files:
            block = _file_content_block(filename, data)
            if block:
                content.append(block)

    instructions = f"""You are a certified medical billing specialist for Puerto Rico payers \
(ASES/Mi Salud, Plan Vital, Triple-S, MMM, MCS, Medicare/FCSO).

You were given the medical record page(s) and claim-lines material above (if any), \
plus pasted claim-lines text below (if any). Read everything provided, then:

1. Extract every billable line item: CPT/HCPCS code, a short plain-English description, \
the primary ICD-10 diagnosis code for that line, any modifier (or "—" if none), units, \
and the billed dollar amount.
2. Cross-reference the claim lines against the medical record. Flag documentation gaps a \
standard scrubber would miss — e.g. a treatment-plan date/signature not present, interactive \
complexity not separately documented, telehealth platform not named, service level not \
supported by the note, prior-authorization reference missing. If no medical record was \
provided, include one docFinding noting that.
3. Flag coding-risk issues: modifier misuse, ICD-10 lacking specificity, upcoding/undercoding \
risk relative to documented complexity. Use code prefix "AI-" for each.

{"PASTED CLAIM LINES TEXT:" if claim_text.strip() else ""}
{claim_text.strip()}

Write docFinding messages and issue text in {"English" if is_en else "Spanish"}. Issue titles/details \
still need both tEn/tEs and dEn/dEs — write the one matching the requested language accurately and \
give a reasonable {"Spanish" if is_en else "English"} counterpart for the other.

Respond with ONLY valid JSON — no markdown fences, no prose outside the JSON object:
{{
  "lines": [{{"cpt":"...", "desc":"...", "icd10":"...", "mod":"...", "units":1, "amount":123.45}}],
  "docFindings": [{{"ok": true, "msg": "..."}}],
  "issues": [{{"code":"AI-...", "sev":"error|warning|info", "tEn":"...", "tEs":"...", "dEn":"...", "dEs":"..."}}]
}}
If nothing billable could be found, return {{"lines": [], "docFindings": [...explaining why...], "issues": []}}."""

    content.append({"type": "text", "text": instructions})

    try:
        response = _client.messages.create(
            model=MODEL,
            max_tokens=2200,
            temperature=0,
            messages=[{"role": "user", "content": content}],
        )
        raw = response.content[0].text.strip()
        if raw.startswith("```"):
            parts = raw.split("```")
            raw = parts[1] if len(parts) > 1 else raw
            if raw.startswith("json"):
                raw = raw[4:].strip()
        return json.loads(raw)
    except Exception as exc:
        logger.warning("Smart Entry extraction failed: %s", exc)
        return None
